### ISSUE TITLE
Confusing terminology

### ISSUE THREAD

**Issue by FranklinChen** [pzol/deterministic#15]
It's great to see comprehensive Ruby implementations of functional programming patterns! I have a concern about the terminology you are using here, however. Rust `Result` is actually exactly the same as Haskell `Either` and Scala `Either`. So calling something else `Either` is very confusing. What you call `Either` is actually a composite validation pattern built on top of success and failure being semigroups and therefore collecting both successes and failures; applicative functor would be the more abstract notion. I'm actually working on a Rust library for patterns for error handling (because I care about collecting errors rather than just bailing on one) and haven't come up with a perfect name for the pattern yet, but `CollectedResult` might be a good one. In any case, I think `Either` would be a bad idea given that it already has a clear, unambiguous meaning.

**Comment by twopoint718** [comment]
The thing that I've seen (e.g. in the [validation package](https://hackage.haskell.org/package/validation-0.5.1)) is that you basically have an Either but the type on the left should have semigroup constraint. That is, the thing on the left is "accumulateable" (and that's it). I've heard the term "validation" used for this sort of thing.
