### ISSUE TITLE
Consider separating Either from Result

### ISSUE THREAD

**Issue by ms-ati** [pzol/deterministic#23]
Hi there, I like what you have here. I have partial work on similar libraries such as Rumonade and Result.

Following the lessons of Scala, Scalaz, and Functional Java, may I recommend that you separate Either (Left | Right) from a Validation class (Success | Failure)?.

Specifically, Either would be a non-biased disjoint union type with only Monadic composition. Once it produces a Left, further operations stay Left. Validation (or Result) on the other hand is a success-biased error combination tool, which allows aggregating multiple errors inside the Failure.

With such a distinction, we could add Applicative tools, for example: lifting a function that takes and returns Integer into a function that takes and returns Validation<Integer>, and automatically aggregates multiple failures. Or, for example, traversing an Array of Integers, applying a function to each which returns a Validation, and ultimately returning a single Validation which contains either a Success with the full Array of results, or a Failure containing all aggregated failures.

Does this sound interesting? I am happy to help if you are interested in this direction.

Regards,
-Marc

**Comment by beezee** [comment]
Was just looking at the issues list to see if someone had considered accumulating failures, +1

**Comment by ms-ati** [comment]
So I just got back from NEScala 2015, where different approaches taken in the Scalactic library's "Or / Every / Good / Bad" and Scalaz's Validation were compared and discussed. Please let me know if you'd like to discuss.

**Comment by pzol** [comment]
Sure, would love to hear!


Piotr
