### ISSUE TITLE
Still active

### ISSUE THREAD

**Issue by willian** [pzol/deterministic#35]
Is this project still active?

**Comment by willian** [comment]
Ok, I believe it's not :/

**Comment by pzol** [comment]
Hey, not much, i have moved to developing in Rust a while ago... but if you want to make MR, happy to process them


Piotr

**Comment by bautrey37** [comment]
We at [Glia](https://github.com/salemove) are maintaining this for the time being. If you open a PR, you can ping me. 

I'll close this issue.
